### ISSUE TITLE
Planets get deleted after submitting to planets and moons endpoint

### ISSUE THREAD

**Issue by skiwi2** [skiwi2/OLog#19]
I have noticed that, right after implementing the ability to store moons, in the Planets table all planets (except one) are marked as deleted, hence it does not seem to be restricted to a single player.

The incident occurred at 16:09:48 local time, as all planets have that time as deletion time.

I have found the following in the access log of my server:

> 127.0.0.1 - - [12/Jan/2016:16:09:48 +0100] "POST /OGNext-0.3-SNAPSHOT/api/userscript/moons HTTP/1.1" 200 38
> 127.0.0.1 - - [12/Jan/2016:16:09:48 +0100] "POST /OGNext-0.3-SNAPSHOT/api/userscript/planets HTTP/1.1" 200 38

It is definitely related to the /moons or /planets endpoint, but I'm unsure which one exactly or what exactly is going on.

**Comment by skiwi2** [comment]
This issue cannot be reproduced.

**Comment by skiwi2** [comment]
This also can happen to moons...

Appears to have something to do with the following error:

> Caused by: grails.validation.ValidationException: Validation Error(s) occurred during save():
> - Field error in object 'com.ognext.Planet' on field 'locations': rejected value [[PlanetLocation(168, Coordinate(165, Universe(2, en, 135), 2, 153, 8), 1970-01-01T00:00:00Z, 2016-01-28T14:53:17.420Z), PlanetLocation(null, Coordinate(161, Universe(2, en, 135), 2, 122, 12), 2016-01-28T14:53:17.420Z, 2016-01-12T15:09:48.512Z)]]; codes [com.ognext.Planet.locations.validator.error.com.ognext.Planet.locations,com.ognext.Planet.locations.validator.error.locations,com.ognext.Planet.locations.validator.error.java.util.List,com.ognext.Planet.locations.validator.error,planet.locations.validator.error.com.ognext.Planet.locations,planet.locations.validator.error.locations,planet.locations.validator.error.java.util.List,planet.locations.validator.error,com.ognext.Planet.locations.locationIntersects.com.ognext.Planet.locations,com.ognext.Planet.locations.locationIntersects.locations,com.ognext.Planet.locations.locationIntersects.java.util.List,com.ognext.Planet.locations.locationIntersects,planet.locations.locationIntersects.com.ognext.Planet.locations,planet.locations.locationIntersects.locations,planet.locations.locationIntersects.java.util.List,planet.locations.locationIntersects,locationIntersects.com.ognext.Planet.locations,locationIntersects.locations,locationIntersects.java.util.List,locationIntersects]; arguments [locations,class com.ognext.Planet,[PlanetLocation(168, Coordinate(165, Universe(2, en, 135), 2, 153, 8), 1970-01-01T00:00:00Z, 2016-01-28T14:53:17.420Z), PlanetLocation(null, Coordinate(161, Universe(2, en, 135), 2, 122, 12), 2016-01-28T14:53:17.420Z, 2016-01-12T15:09:48.512Z)]]; default message [Attribuut [{0}] van entiteit [{1}] met waarde [{2}] is niet geldig]
>   
>   at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:153) ~[AbstractHibernateGormInstanceApi.class:na]
>   at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:101) ~[GormInstanceApi.class:na]
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
>   at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
>   at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210) ~[PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.class:2.4.5]
>   at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71) ~[PogoMetaMethodSite.class:2.4.5]
>   at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[CallSiteArray.class:2.4.5]
>   at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:76) ~[PogoMetaMethodSite.class:2.4.5]
>   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[AbstractCallSite.class:2.4.5]
>   at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:112) ~[GormEntity$Trait$Helper.class:na]
>   at org.grails.datastore.gorm.GormEntity$Trait$Helper$save$1.call(Unknown Source) ~[na:na]
>   at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[CallSiteArray.class:2.4.5]
>   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[AbstractCallSite.class:2.4.5]
>   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[AbstractCallSite.class:2.4.5]
>   at com.ognext.Planet.save(Planet.groovy) ~[Planet.class:na]
>   at com.ognext.Planet.save(Planet.groovy) ~[Planet.class:na]
>   at org.grails.datastore.gorm.GormEntity$save.call(Unknown Source) ~[na:na]
>   at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[CallSiteArray.class:2.4.5]
>   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[AbstractCallSite.class:2.4.5]
>   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) ~[AbstractCallSite.class:2.4.5]
>   at com.ognext.PlanetService.$tt__storePlanetLocation(PlanetService.groovy:39) ~[PlanetService.class:na]
>   at com.ognext.PlanetService$_storePlanetLocation_closure3.doCall(PlanetService.groovy) ~[PlanetService$_storePlanetLocation_closure3.class:na]
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
>   at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
>   at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[CachedMethod.class:2.4.5]
>   at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[MetaMethod.class:2.4.5]
>   at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[ClosureMetaClass.class:2.4.5]
>   at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019) ~[MetaClassImpl.class:2.4.5]
>   at groovy.lang.Closure.call(Closure.java:426) ~[Closure.class:2.4.5]
>   at groovy.lang.Closure.call(Closure.java:442) ~[Closure.class:2.4.5]
>   at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:93) ~[GrailsTransactionTemplate$2.class:3.0.9]
>   at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[TransactionTemplate.class:4.1.7.RELEASE]
>   at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:90) ~[GrailsTransactionTemplate.class:3.0.9]
>   at com.ognext.PlanetService.storePlanetLocation(PlanetService.groovy) ~[PlanetService.class:na]
>   at com.ognext.PlanetService$storePlanetLocation$0.call(Unknown Source) ~[na:na]
>   at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[CallSiteArray.class:2.4.5]
>   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[AbstractCallSite.class:2.4.5]
>   at com.ognext.api.UserscriptController$_planets_closure6.doCall(UserscriptController.groovy:76) ~[UserscriptController$_planets_closure6.class:na]
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
>   at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
>   at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[CachedMethod.class:2.4.5]
>   at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[MetaMethod.class:2.4.5]
>   at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[ClosureMetaClass.class:2.4.5]
>   at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019) ~[MetaClassImpl.class:2.4.5]
>   at groovy.lang.Closure.call(Closure.java:426) ~[Closure.class:2.4.5]
>   at groovy.lang.Closure.call(Closure.java:442) ~[Closure.class:2.4.5]
>   at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030) ~[DefaultGroovyMethods.class:2.4.5]
>   at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015) ~[DefaultGroovyMethods.class:2.4.5]
>   at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056) ~[DefaultGroovyMethods.class:2.4.5]
>   at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source) ~[dgm$162.class:2.4.5]
>   at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274) ~[PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.class:2.4.5]
>   at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) ~[PojoMetaMethodSite.class:2.4.5]
>   at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[CallSiteArray.class:2.4.5]
>   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[AbstractCallSite.class:2.4.5]
>   at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[AbstractCallSite.class:2.4.5]
>   at com.ognext.api.UserscriptController.planets(UserscriptController.groovy:67) ~[UserscriptController.class:na]
>   ... 64 common frames omitted
